birch-standards-picker.css
birch-standards-picker.html
test/birch-standards-picker-test.html

Passing in the disabled property will remove any placeholder text as well.
See https://github.com/FamilySearchElements/birch-typeahead/pull/8

Pass 'disabled' property to pass to birch-typeahead

---

birch-standards-picker.html

This is to catch key down events for scrolling with arrows and 'enter'. Catching 'enter' here prevents the parent form from submitting when a standard is selected.

Add on-keydown listener to birch-typeahead version of standards picker.

---

birch-standards-picker.html

It checks for changes after it make the change itself, causing a no-op every time.

Fix _updateData not firing event

---

birch-standards-picker.html

In the scenario where a user enters custom text that does not exactly match any standard and then selected the first typeahead option while there is more than one option, not all data that was supposed to be present was included. This addresses that issue.
@rosemariesadler please review to confirm this addresses the issue you're seeing.

Include missing options data

---

birch-standards-picker.html
bower.json

See TW-743.
This change adds formalText to the `data` object. This will allow those who are saving dates to pass that same param back to the endpoints.

bugfix: pass through formalDate so that we can save dates correctly

---

birch-standards-picker.html

* Remove `max-width` from standards selector button
* Decrease typeahead option `min-height` from the default `72px` to `50px`
* Delete `customText` when `customText` and `standardText` are identical (update docs to reflect this behavior)
* Reset more properties in the `reset` function
* Programmatically focus the standards button on click because firefox doesn't do it automatically
* Fix a typo

Improvements

---

birch-standards-picker.html

Data tests were needed to help automated tests find elements on the page.
Data tests were added to elements to check if a place/date is standardized.

Added data tests to various elements

---

birch-standards-picker.html

* Highlight the selected standard option on load
* Adding a `title` attribute to the standard select button so there's a hover tooltip
* Fix a bug selecting the typeahead option under the one clicked
* Fix a bug causing the standard select to show even when a standard is selected
* Fix a bug preventing the standard icon within the input from appearing on load

A few handy updates from your friendly neighborhood Spiderman.

---

birch-standards-picker.html

to `standards-picker` or `typeahead`.
This is to resolve request made in JIRA TW-1248

Allowing property to show if user has made changes

---

birch-standards-picker.html

We need this attribute so that fs-dialog will properly "loop" when tabbing through elements.

make standards picker work inside of fs-dialog v5

---

birch-standards-picker.html
bower.json

- The truncation on places dropdown menu happens even though there's enough room for it to happen.

TW-1429 Fix

---

birch-standards-picker.html

- Allowed standardized date/place text to ellipsis
- Also added title to divs to allow hover to show full text when truncated.
- Input label was not included in reset function
* This was causing incorrect label rendering when different standards-picker types used for same picker instance

Allowing for narrow use

---

birch-standards-picker.html

TW-1508: Removes reset of the inputLabel property.
With this statement, the input label that was specified when the component is loaded gets removed.

TW-1508: Removes reset of the inputLabel property.

---

birch-standards-picker.html
test/birch-standards-picker-test.html

Added properties to allow setting a custom placeholder and a custom URL to use to fetch data.
We'd really like to use this component on Lightyear, but we need a couple very minor adjustments to allow for a couple different use cases. These adjustments won't change anything for any components already being used on the site.

Add properties for custom placeholder and URL

---

birch-standards-picker.html
bower.json

Add the following CSS mixins in order to style the input field:
* `--birch-standards-picker-input`
* `--birch-standards-picker-input-focus`

Add input and input-focus mixins

---

birch-standards-picker.html
bower.json
package.json

- Result of error: Once `inputLabel` has been set, it will use the same `inputLabel` even if the `standardType` has been changed
> If applied, this commit will **_Fix input label not updating with a change to `standardType`_**.
Fixes: JIRA PS-3587

Fixing "out of sync" input label when switching between date/place

---

birch-standards-picker.html
bower.json
package.json

I introduced a bug when merging this PR: https://github.com/fs-webdev/birch-standards-picker/pull/46 where you can no longer specify a custom input label. This now uses an internal variable to set the inputLabel on the birch-typeahead so that if a user sets `inputLabel`, we always use that, but we default back to the correct one on type change even if the user hasn't set one or unsets the custom field.

make it so that you can set a custom inputLabel again while still switching it if no custom label is set to the default for the standard type

---

birch-standards-picker.html
bower.json
package.json

These are very safe changes because they are comments. I updated the comments so that this won't show up in our DTM audits.
> If applied, this commit will **_update tree-data comments_**.
Review: [CONTRIBUTING.md](/.github/CONTRIBUTING.md)
- Updated tree-data comments to reflect DTM paths.

Updates DTM paths.

---

birch-standards-picker.html
bower.json
package.json

We need a way to get back dates and places in a different language than what the browser has.  We have record data in say German and we want the patron to enter the date or place in the language of the record instead of the browser language setting.

Add api look up lang override

---

birch-standards-picker.html
bower.json
package.json
wct.conf.json

* if the standards picker menu isn't visible when it displays, this gives the consumer the option to scroll it into view
depends on: https://github.com/fs-webdev/birch-typeahead/pull/28 to work.
chrome:
safari:
firefox:
Note: Jeff is cool with the jumpy behavior in firefox

feature: add scrollIntoViewIfNeededOnListOpen

---

birch-standards-picker.html
bower.json
package.json
wct.conf.json

* use scroll into view instead, which has the same support matrix as scrollBy, but it actually works in edge instead of just saying it works in edge
* lower coverage threshhold

bugfix: scrollBy not supported on edge
